# * GitHub Sponsors configuration
# * Uncomment and configure if you want to enable sponsorship

# github: [ciphera-net]
# patreon: # your-patreon-username
# open_collective: # your-open-collective-name
# ko_fi: # your-ko-fi-username
# custom: ["https://ciphera.net/donate"]
